name: Generate Daily AI Image

on:
  schedule:
    - cron: "0 1 * * *"  # Every day at 6:30 AM IST
  workflow_dispatch:

jobs:
  run-generation:
    runs-on: ubuntu-latest

    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run main script
        run: python main.py
